### ISSUE TITLE
Crash calling Mono.Cecil.ModuleDefinition.get_Types

### ISSUE THREAD

**Issue by Bretanark** [OpenCover/opencover#298]
Hi, I've encountered crashes when covering a specific unit test dll.  I suspected problems with Moq, but another dll using Moq works fine.  Both dlls reference .NET 4.5.2, but it's possible that only the broken one actually uses 4.5.2 features.  I notice that build 4.5.3926 from issue 288 uses Mono.Cecil version 0.9.5.0, which when retrieved from nuget doesn't have a net45 folder, whereas version 0.9.6.0 does.  Perhaps updating to the latest Mono.Cecil version might fix the problem.

Below are the crash details

Thanks

- Brent

"C:\Users\Brent.Clark\AppData\Local\Apps\OpenCover\OpenCover.Console.exe"  -target:"C:\Program Files (x86)\NUnit 2.6.2\bin\nunit-console-x86.exe" -targetargs:"\\AP-CHC-LT003\Projects\Trunk\Axiom\Tests\ServiceUnitTests\bin\Slave1\Ax.ServiceUnitTests.d
ll /Fixture=Ax.Services.UnitTests.Impl.Services.Main.NoteServiceTests /Xml=\\AP-CHC-LT003\Projects\trunk\Log\2015\04\27\1613\Ax.Services.UnitTests.Impl.Services.Main.NoteServiceTests.xml /noLogo /noShadow /Labels  /exclude=Performance" -output:"\\AP-
CHC-LT003\Projects\trunk\Log\2015\04\27\1613\Ax.Services.UnitTests.Impl.Services.Main.NoteServiceTests.OpenCover.xml" -mergebyhash -excludebyfile:*Moq*
Executing: C:\Program Files (x86)\NUnit 2.6.2\bin\nunit-console-x86.exe
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5

Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Mono.Cecil.MetadataReader.AddNestedMapping(UInt32 declaring, UInt32 nested)
   at Mono.Cecil.MetadataReader.InitializeNestedTypes()
   at Mono.Cecil.MetadataReader.InitializeTypeDefinitions()
   at Mono.Cecil.MetadataReader.ReadTypes()
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.ModuleDefinition.get_Types()
   at OpenCover.Framework.Symbols.CecilSymbolManager.GetFiles()
   at OpenCover.Framework.Model.InstrumentationModelBuilder.CreateModule(Boolean full)
   at OpenCover.Framework.Model.InstrumentationModelBuilder.BuildModuleModel(Boolean full)
   at OpenCover.Framework.Service.ProfilerCommunication.TrackAssembly(String modulePath, String assemblyName)
   at OpenCover.Framework.Communication.MessageHandler.StandardMessage(MSG_Type msgType, IManagedCommunicationBlock mcb, Action`2 chunkReady, Action`2 offloadHandling)
   at OpenCover.Framework.Communication.CommunicationManager.HandleCommunicationBlock(IManagedCommunicationBlock mcb, Action`2 offloadHandling)
   at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass24.<ProcessBlock>b__22(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by sawilde** [comment]
We actually use a custom build of mono.cecil as the nuget version at the time didn't correctly handle the latest PDBs. 0.9.6 of Mono.Cecil was only just released (25th April) so I haven't had chance to evaluate it yet but it'll be good to have a new version after so many years.

Do you have a way for me to repeat it so I can test if the upgrading Mono.Cecil resolves your issue?

**Comment by sawilde** [comment]
Issue #248 was the reason we used a custom build.

Hopefully the .net4 build in the package will be able to work as I don't want to force people to .NET4.5.2 unnecessarily, in the end it only has to parse the data in the assembly it does not actually have to utilize it itself.

**Comment by Bretanark** [comment]
I can't provide you a repro as the scenario I've got is too complicated.  I'm happy to try a special build.  Otherwise I assume that I might be able to download the source for Mono.Cecil and OpenCover to step into this myself.  I'm new to GitHub, so I'm not sure how to do this - any tips welcome.

**Comment by sawilde** [comment]
no worries - I have pulled the latest mono.cecil and just running it through it's paces

**Comment by Bretanark** [comment]
I've found that one particular dll of ours causes problems with Mono.Cecil, which also affects Reflector.
I worked out the general area, but it seems to be a combination of dozens of files, of which when I remove a few, everything's fine.
Thanks for trying out the latest though.

**Comment by sawilde** [comment]
No worries - it actually addresses some previous issues that I used a patch for
