### ISSUE TITLE
ArgumentOutOfRangeException in SaveVisitData()

### ISSUE THREAD

**Issue by dbaker-sis-tv** [OpenCover/opencover#354]
When running our unit tests last night from Team City (via a Nant script) OpenCover exited with return code was 255.  We are using OpenCover v4.6.166 from Nuget.

The stack trace in our build output is: 
[19:03:31]     [exec] Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
[19:03:31]     [exec] Parameter name: startIndex
[19:03:31]     [exec]    at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
[19:03:31]     [exec]    at OpenCover.Framework.Persistance.BasePersistance.SaveVisitData(Byte[] data) in c:\projects\opencover\main\OpenCover.Framework\Persistance\BasePersistance.cs:line 494
[19:03:31]     [exec]    at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass7.<SaveVisitData>b__6(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 142
[19:03:31]     [exec]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[19:03:31]     [exec]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[19:03:31]     [exec]    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[19:03:31]     [exec]    at System.Threading.ThreadPoolWorkQueue.Dispatch()

I downloaded the OpenCover source code today and the line in question appears to be BasePersistance.cs line 534 (suggesting this file has changed since the version from NuGet - the stack trace says line 494):
var nCount = BitConverter.ToUInt32(data, 0);

I'm guessing that the only way this could throw ArgumentOutOfRangeException would be if data was an empty array.  If data was null it would throw an ArgumentNullException.

I've only seen this error once (the same unit tests have ran successfully multiple other times) so I doubt it is easily to reproduce.  If you need any extra data files from me, please let me know.

**Comment by dbaker-sis-tv** [comment]
Sorry - it looks like this issue has been addressed already - I should have looked at the release notes first.  https://github.com/OpenCover/opencover/issues/329
