### ISSUE TITLE
The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by magmax** [OpenCover/opencover#375]
Some times I receive this error:

```
Application: OpenCover.Console.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.BitConverter.ToUInt32(Byte[], Int32)
   at OpenCover.Framework.Persistance.BasePersistance.SaveVisitData(Byte[])
   at OpenCover.Framework.Manager.ProfilerManager+<>c__DisplayClass7.<SaveVisitData>b__6(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

It shows a window and stacks the jenkins builds.

I'm using opencover.console version 4.6.166, with these parameters:

```
OpenCover.Console.exe -returntargetcode -target:c:\whatever\nunit3-console.exe "-targetargs:file1 file2 file3 --result:whatever.xml;format=nunit2" -register:user -output:whatever_opencover.xml
```

**Comment by molnargab** [comment]
Seems similar to #329. Could you provide some diagnostics with 4.6.210? It's been enhanced to have some more details.

**Comment by magmax** [comment]
with 4.6.210:

```
Unhandled Exception: Unhandled Exception:
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ResetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Reset()
   at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass30.<ProcessBlock>b__2e(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 280
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ResetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Reset()
   at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass30.<ProcessBlock>b__2e(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 280
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ResetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Reset()
   at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass30.<ProcessBlock>b__2e(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 280
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by MaceWindu** [comment]
This is exception from #350

**Comment by magmax** [comment]
I'm not sure if it is related, but exceptions are different.

Anyways, it happens about 75% times.

**Comment by sawilde** [comment]
@magmax - I suggest you upgrade to the latest version 2.6.166 is over 3 years old

**Comment by magmax** [comment]
You are right: It was 4.6.166. It was a typo. I've corrected it in the first comment.

**Comment by sawilde** [comment]
Can you try this release to see if it corrects your issue
https://www.nuget.org/packages/OpenCover/4.6.247-rc 
https://github.com/OpenCover/opencover/releases/tag/4.6.247-rc

**Comment by magmax** [comment]
I've tried it.

It seems there was a problem in nunit3, and now it is correctly managed by opencover.

But option "-output" doesn't works with this version... Should I close this issue and create a new one?

**Comment by ddur** [comment]
@magmax 
Yes please.
