### ISSUE TITLE
Problem 153478: OpenCover.Framework.ProfilerRegistration.ExecuteRegsvr32

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#457]
https://drdump.com/Bug.aspx?ProblemID=153478
could be related to
https://drdump.com/Problem.aspx?ProblemID=173556

    System.InvalidOperationException
     at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
     at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
     at OpenCover.Framework.ProfilerRegistration.ExecuteRegsvr32(Boolean userRegistration, Boolean register, Boolean is64) in ProfilerRegistration.cs:62
     at OpenCover.Framework.ProfilerRegistration.ExecuteRegsvr32(Boolean userRegistration, Boolean register) in ProfilerRegistration.cs:52
     at OpenCover.Framework.ProfilerRegistration.Register(Registration registration) in ProfilerRegistration.cs:34
     at OpenCover.Console.Program.RunWithContainer(CommandLineParser parser, Bootstrapper container, IPersistance persistance) in Program.cs:157
     at OpenCover.Console.Program.Main(String[] args) in Program.cs:66

**Comment by ddur** [comment]
Line 62 is not wraped with try/catch (or tested for exception condition)
```
InvalidOperationException: No file name was specified in the startInfo parameter's FileName property.
-or- The UseShellExecute property of the startInfo parameter is true and the RedirectStandardInput, RedirectStandardOutput, or RedirectStandardError property is also true.
-or-The UseShellExecute property of the startInfo parameter is true and the UserName property is not null or empty or the Password property is not null.
```

**Comment by sawilde** [comment]
I doubt it is any of the conditions described in the MSDN docs for [Process.Start](https://msdn.microsoft.com/library/0w4h05yb(v=vs.100).aspx) otherwise it would always happen - wouldn't it?

**Comment by ddur** [comment]
>I doubt it is any of the conditions described in the MSDN docs for Process.Start otherwise it would always happen - wouldn't it?

I do not know, I would wrap it with try/catch anyway.

**Comment by sawilde** [comment]
got a drdump report for rc 410 so gong to wrap the call and add user messages

**Comment by ddur** [comment]
I wrote small ```OpenCover.Framework.Utility.LogHelper.InformUser``` method. Maybe it fits your needs. If not you can add more.

**Comment by sawilde** [comment]
I am sure we could refactor to use it
