### ISSUE TITLE
Problem 159608: OpenCover.Framework.Persistance.FilePersistance.SaveCoverageFile

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#458]
https://drdump.com/Problem.aspx?ProblemID=159608
related to 
https://drdump.com/Problem.aspx?ProblemID=177515
https://drdump.com/Problem.aspx?ProblemID=176897
https://drdump.com/Problem.aspx?ProblemID=176924
https://drdump.com/Problem.aspx?ProblemID=177515
https://drdump.com/Problem.aspx?ProblemID=180477	

    System.IO.IOException
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
    at System.IO.FileStream..ctor(String path, FileMode mode)
    at OpenCover.Framework.Persistance.FilePersistance.SaveCoverageFile() in FilePersistance.cs:87
    at OpenCover.Framework.Persistance.FilePersistance.Commit() in FilePersistance.cs:80
    at OpenCover.Framework.Service.ProfilerCommunication.Stopping() in ProfilerCommunication.cs:98
    at OpenCover.Framework.Communication.MessageHandler.Complete() in MessageHandler.cs:349
    at OpenCover.Framework.Communication.CommunicationManager.Complete() in CommunicationManager.cs:93
    at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass7.<SaveVisitData>b__6(Object state) in ProfilerManager.cs:161
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
    at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by sawilde** [comment]
Seems we have a number of issues around saving a file - probably permissions related - e.g. trying to save into ProgramFiles or some other restricted location.

It might be worth testing the file location before the coverage run and letting the user know the location is unusable. e.g. The location 'path to output file' cannot be used. Please check the path suppplied exists or that your account has permissions to that location.
