### ISSUE TITLE
Problem 172651: OpenCover.Framework.Manager.ProfilerManager.ProcessMessages

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#459]
https://drdump.com/Bug.aspx?ProblemID=172651

    System.InvalidOperationException
    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
    at OpenCover.Framework.Manager.ProfilerManager.ProcessMessages(WaitHandle[] handles) in ProfilerManager.cs:203
    at OpenCover.Framework.Manager.ProfilerManager.RunProcess(Action`1 process, String[] servicePrincipal) in ProfilerManager.cs:90
    at OpenCover.Console.Program.RunWithContainer(CommandLineParser parser, Bootstrapper container, IPersistance persistance) in Program.cs:157
    at OpenCover.Console.Program.Main(String[] args) in Program.cs:66

**Comment by ddur** [comment]
Is that from release or from recent build?

**Comment by ddur** [comment]
Last reported in 4.6.261.0
Fixed in 4.6.363.0

**Comment by sawilde** [comment]
@ddur the change you have reference is for MemoryManager.cs

**Comment by ddur** [comment]
If it is not, DrDump will reopen that issue again.
