### ISSUE TITLE
Problem 173802: OpenCover.Framework.Filter.GetAssemblyClassName

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#477]
https://drdump.com/Problem.aspx?ProblemID=173802
relates to
https://drdump.com/Problem.aspx?ProblemID=173280

````
System.InvalidOperationException
 at OpenCover.Framework.Filter.GetAssemblyClassName(String assemblyClassName, Boolean useRegEx, FilterType& filterType, String& assemblyName, String& className, String& processName)
 at OpenCover.Framework.Filter.AddFilter(String assemblyClassName)
 at System.Collections.Generic.List`1.ForEach(Action`1 action)
 at OpenCover.Framework.Filter.BuildFilter(CommandLineParser parser)
 at OpenCover.Console.Program.BuildFilter(CommandLineParser parser)
 at OpenCover.Console.Program.Main(String[] args)
````

````
System.InvalidOperationException
 at OpenCover.Framework.Filtering.FilterHelper.ValidateAndEscape(String match, String notAllowed)
 at OpenCover.Framework.Filter.AddFilter(String assemblyClassName)
 at System.Collections.Generic.List`1.ForEach(Action`1 action)
 at OpenCover.Framework.Filter.BuildFilter(CommandLineParser parser)
 at OpenCover.Console.Program.BuildFilter(CommandLineParser parser)
 at OpenCover.Console.Program.Main(String[] args)
````

**Comment by sawilde** [comment]
This error is intentional in that we were using InvalidOperationException as error flow. I've refactored to publish a helpful user message and to not generate an exception that will be published to DrDump.
