### ISSUE TITLE
Problem 183257: OpenCover.Console.Program.RunProcess

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#491]
https://drdump.com/Problem.aspx?ProblemID=183257

````
OpenCover.Framework.ExitApplicationWithoutReportingException
 at OpenCover.Console.Program.RunProcess(CommandLineParser parser, Action`1 environment) in Program.cs:380
 at OpenCover.Console.Program.<>c__DisplayClass6.<RunWithContainer>b__3(Action`1 environment) in Program.cs:166
 at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass3.<SetProfilerAttributes>b__1(Object state) in ProfilerManager.cs:127
 at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
````

**Comment by sawilde** [comment]
This exception should be caught and hidden as it is a false-positive

**Comment by ddur** [comment]
I have SharpDevelop IDE warning at return, maybe is false
```'SetProfilerAttributes': A return keyword must be followed by any expression when method returns a value```
```
            if (dictionary == null) return;
            SetProfilerAttributesOnDictionary(profilerKey, profilerNamespace, dictionary);
            environmentKeyRead.Set();
```
wrapping statements with ```if``` condition will do no harm
```
            if (dictionary != null) {
                SetProfilerAttributesOnDictionary(profilerKey, profilerNamespace, dictionary);
                environmentKeyRead.Set();
            }
```

**Comment by sawilde** [comment]
you're right it is false and it will do no harm either - I think the `Action<Action<>>` confused it
