### ISSUE TITLE
Problem 183311: OpenCover.Framework.Persistance.BasePersistance.TransformSequences_RemoveCompilerGeneratedBranches

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#492]
https://drdump.com/Problem.aspx?ProblemID=183311

````
System.IndexOutOfRangeException
 at OpenCover.Framework.Persistance.BasePersistance.TransformSequences_RemoveCompilerGeneratedBranches(IEnumerable`1 methods, SourceRepository sourceRepository) in BasePersistance.cs:637
 at OpenCover.Framework.Persistance.BasePersistance.TransformSequences() in BasePersistance.cs:551
 at OpenCover.Framework.Persistance.BasePersistance.Commit() in BasePersistance.cs:162
 at OpenCover.Framework.Persistance.FilePersistance.Commit() in FilePersistance.cs:109
 at OpenCover.Framework.Service.ProfilerCommunication.Stopping() in ProfilerCommunication.cs:97
 at OpenCover.Framework.Communication.MessageHandler.Complete() in MessageHandler.cs:363
 at OpenCover.Framework.Communication.CommunicationManager.Complete() in CommunicationManager.cs:102
 at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass7.<SaveVisitData>b__6(Object state) in ProfilerManager.cs:185
 at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
````

**Comment by ddur** [comment]
This is weird, we looked at doctor dump at same time. :)

**Comment by ddur** [comment]
@sawilde 
Can you remove last rc from nuget?

**Comment by ddur** [comment]
Shall we in the future run Coverity test before release?

**Comment by sawilde** [comment]
> Can you remove last rc from nuget?
no nuget is fixed we can make another `rc` though

**Comment by ddur** [comment]
I see now what is going here. 
Method is checked before to have at least one SequencePoint.
This (not generated) method has SequencePoints but no sequence point with same file id as method file id. Unexpected. I wish I could see that source & coverage report.
