### ISSUE TITLE
Problem 186323: OpenCover.Framework.Manager.ProfilerManager.ProcessMessages

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#532]
looks like the list is being manipulated whilst being iterated

````
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
 at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
 at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
 at OpenCover.Framework.Manager.ProfilerManager.ProcessMessages(WaitHandle[] handles) in ProfilerManager.cs:235
 at OpenCover.Framework.Manager.ProfilerManager.RunProcess(Action`1 process, String[] servicePrincipal) in ProfilerManager.cs:120
 at OpenCover.Console.Program.RunWithContainer(CommandLineParser parser, Bootstrapper container, IPersistance persistance) in Program.cs:185
 at OpenCover.Console.Program.Main(String[] args) in Program.cs:70
````

**Comment by sawilde** [comment]
look to change the list returned into something immutable (i.e. a copy)
