### ISSUE TITLE
Random IndexOutOfRangeException 

### ISSUE THREAD

**Issue by trivalik** [OpenCover/opencover#539]
We get randomly this with the 4.6.515 rc:

```
...
Unhandled Exception: System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.Windows.Input.TextServicesContext.StopTransitoryExtension()
   at System.Windows.Input.TextServicesContext.Uninitialize(Boolean appDomainShutdown)
   at System.Windows.Input.TextServicesContext.TextServicesContextShutDownListener.OnShutDown(Object target, Object sender, EventArgs e)
   at MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
Committing...
At: CurrentDomainOnUnhandledException
An System.IndexOutOfRangeException occured: Index was outside the bounds of the array.
stack:    at OpenCover.Framework.Persistance.BasePersistance.TransformSequences_RemoveCompilerGeneratedBranches(IEnumerable`1 methods, SourceRepository sourceRepository) in c:\projects\opencover\main\OpenCover.Framework\Persistance\BasePersistance.cs:line 637
   at OpenCover.Framework.Persistance.BasePersistance.TransformSequences() in c:\projects\opencover\main\OpenCover.Framework\Persistance\BasePersistance.cs:line 551
   at OpenCover.Framework.Persistance.BasePersistance.Commit() in c:\projects\opencover\main\OpenCover.Framework\Persistance\BasePersistance.cs:line 162
   at OpenCover.Framework.Persistance.FilePersistance.Commit() in c:\projects\opencover\main\OpenCover.Framework\Persistance\FilePersistance.cs:line 109
   at OpenCover.Framework.Service.ProfilerCommunication.Stopping() in c:\projects\opencover\main\OpenCover.Framework\Service\ProfilerCommunication.cs:line 97
   at OpenCover.Framework.Communication.MessageHandler.Complete() in c:\projects\opencover\main\OpenCover.Framework\Communication\MessageHandler.cs:line 363
   at OpenCover.Framework.Communication.CommunicationManager.Complete() in c:\projects\opencover\main\OpenCover.Framework\Communication\CommunicationManager.cs:line 102
   at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass7.<SaveVisitData>b__6(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 186
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
A report has been sent to the OpenCover development team...
```

I have no idea from where this COM object is coming from because in tests is it not used.

**Comment by sawilde** [comment]
I don't think you are running 4.6.515 as the line numbers don't match for that release. I think you are running 4.6.434.

This defect was detected by our bug tracking system and fixed for 4.6.476. - https://github.com/opencover/opencover/pull/499

please try the latest RC

**Comment by trivalik** [comment]
Maybe you are right. Then we can close this issue

**Comment by sawilde** [comment]
> Maybe you are right. Then we can close this issue

Have you tried 515?

**Comment by trivalik** [comment]
I guess it was short before I updated to 515. Since this, it was never happen.
