### ISSUE TITLE
Can't build OpenCover

### ISSUE THREAD

**Issue by AdamOrHd123** [OpenCover/opencover#638]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [X] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Build should succeed

### Actual Behavior
Build fails.
C:\Coverage\OpenCover-opencover-df77281>build

Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'NAnt.Console.ConsoleStub' threw an exception. ---> System.Security.SecurityEx
ception: Request for the permission of type 'System.Security.Permissions.FileIOP
ermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5619
34e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMa
rk& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, S
tackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.AppDomainSetup.VerifyDir(String dir, Boolean normalize)
   at System.AppDomain.get_BaseDirectory()
   at log4net.Config.XmlConfiguratorAttribute.Configure(Assembly sourceAssembly,
 ILoggerRepository targetRepository)
   at log4net.Core.DefaultRepositorySelector.ConfigureRepository(Assembly assemb
ly, ILoggerRepository repository)
   at log4net.Core.DefaultRepositorySelector.CreateRepository(Assembly repositor
yAssembly, Type repositoryType, String repositoryName, Boolean readAssemblyAttri
butes)
   at log4net.Core.DefaultRepositorySelector.CreateRepository(Assembly repositor
yAssembly, Type repositoryType)
   at log4net.Core.DefaultRepositorySelector.GetRepository(Assembly repositoryAs
sembly)
   at log4net.Core.LoggerManager.GetLogger(Assembly repositoryAssembly, String n
ame)
   at log4net.LogManager.GetLogger(Assembly repositoryAssembly, String name)
   at log4net.LogManager.GetLogger(Type type)
   at NAnt.Console.ConsoleStub..cctor()
   --- End of inner exception stack trace ---
   at NAnt.Console.ConsoleStub.Main(String[] args)

### Steps to reproduce the problem:

Build the opencover and see an exception.

**Comment by sawilde** [comment]
can't reproduce

**Comment by MyqlG** [comment]
Right click on the zip you downloaded (it will probably show up as blocked).
Click the unblock button.
Install and enjoy.
