### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by jdege** [OpenCover/opencover#664]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ X] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

Encountered a System.AccessViolationException when running OpenCover.

### Steps to reproduce the problem:

Unable to reproduce.

Using OpenCover.4.6.519

`C:\Jenkins\workspace\KorTerra-Builds\KT-ALL-Trunk-Build>packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"/Logger:trx test_xx_db\bin\Release\test_xx_db.dll test_xx_shared\bin\Release\test_xx_shared.dll test_kt_db\bin\Release\test_kt_db.dll test_kt_shared\bin\Release\test_kt_shared.dll test_kt_api\bin\Release\test_kt_api.dll" -excludebyattribute:*.TestClass*;*.TestMethod*;*.ExcludeFromCoverage* -register:user -output:TestResults\outputCoverage.xml 
Executing: D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.VisualStudio.Telemetry.SessionChannel.BaseAppInsightsClientWrapper.TrackEvent(EventTelemetry ev)
   at Microsoft.VisualStudio.Telemetry.SessionChannel.BaseAppInsightsSessionChannel.PostEvent(TelemetryEvent telemetryEvent)
   at Microsoft.VisualStudio.Telemetry.SessionChannel.BaseAppInsightsSessionChannel.PostEvent(TelemetryEvent telemetryEvent, IEnumerable`1 args)
   at Microsoft.VisualStudio.Telemetry.EventProcessorRouter.RouteEvent(TelemetryEvent telemetryEvent, String sessionId, Boolean isDropped)
   at Microsoft.VisualStudio.Telemetry.EventProcessor.ProcessEvent(TelemetryEvent telemetryEvent)
   at Microsoft.VisualStudio.Telemetry.SessionChannel.EventProcessorChannel.ProcessEvents()
   at Microsoft.VisualStudio.Telemetry.TelemetryTaskTimer.<>c__DisplayClass11_0.<Start>b__0(Task previousTask)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.StandardTaskContinuation.Run(Task completedTask, Boolean bCanInlineContinuationTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.Task.DelayPromise.Complete()
   at System.Threading.Tasks.Task.<>c.<Delay>b__274_1(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
Passed   getListOfNewEmergenciesTest
Passed   testAllCustomers
Passed   testFindACustomer
Passed   testDontFindACustomer
Passed   testRemoveACustomer
Passed   testAddACustomer
Passed   TestLogging
Passed   testReadLongArray
Passed   testWriteLongArray
Passed   testReadStringArray
Passed   testWriteStringArray
[....]
`

**Comment by sawilde** [comment]
unable to repeat - is the error message coming from your application being covered or opencover? I sspect the former as OpenCover does not use/reference `Microsoft.VisualStudio.Telemetry`.

If you are unable to repeat then it is just one of those things.
