### ISSUE TITLE
Random ObjectDisposed Exceptions, in current release

### ISSUE THREAD

**Issue by benrr101** [OpenCover/opencover#669]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2 **via AppVeyor Visual Studio 2015 image**
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known. **It is known, but was allegedly fixed, see #350**

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Tests should always execute without exception from OpenCover.

### Actual Behavior
Randomly, OpenCover will fail when running by throwing an ObjectException on our build.

```
=== TEST EXECUTION SUMMARY ===

   Microsoft.SqlTools.ServiceLayer.IntegrationTests  Total: 115, Errors: 0, Failed: 0, Skipped: 0, Time: 114.776s

SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.
At: Program.Main
An System.ObjectDisposedException occured: Safe handle has been closed
stack:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.SafeNativeMethods.ReleaseSemaphore(SafeWaitHandle handle, Int32 releaseCount, Int32& previousCount)
   at System.Threading.Semaphore.Release(Int32 releaseCount)
   at OpenCover.Framework.Manager.MemoryManager.ManagedCommunicationBlock.<Dispose>b__27(Semaphore s) in c:\projects\opencover\main\OpenCover.Framework\Manager\MemoryManager.cs:line 255
   at OpenCover.Framework.HelperExtensions.Do[T](T value, Action`1 action) in c:\projects\opencover\main\OpenCover.Framework\HelperExtensions.cs:line 18
   at OpenCover.Framework.Manager.MemoryManager.ManagedCommunicationBlock.Dispose() in c:\projects\opencover\main\OpenCover.Framework\Manager\MemoryManager.cs:line 252
   at OpenCover.Framework.HelperExtensions.Do[T](T value, Action`1 action) in c:\projects\opencover\main\OpenCover.Framework\HelperExtensions.cs:line 18
   at OpenCover.Framework.Manager.MemoryManager.Dispose() in c:\projects\opencover\main\OpenCover.Framework\Manager\MemoryManager.cs:line 416
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at OpenCover.Framework.Bootstrapper.Dispose() in c:\projects\opencover\main\OpenCover.Framework\Bootstrapper.cs:line 87
   at OpenCover.Console.Program.Main(String[] args) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 70

A report has been sent to the OpenCover development team.
If you are unable to resolve the issue please contact the OpenCover development team see https://www.github.com/opencover/opencover/issues
```

### Steps to reproduce the problem:
Since this is a very difficult to repro issue, I'll give you our detailed info to help you folks figure out what's going on. However, since we most frequently see this issue in AppVeyor CI builds, you won't be able to perfectly replicate the issue.
* Pull latest dev branch of https://github.com/microsoft/sqltoolsservice
* In test/CodeCoverage run integration.bat, which launches a Gulp script that will install opencover nuget packages, build the entire project, launch each test project with opencover, and merge all the reports together.
* Randomly, the opencover run will fail -- most frequently when running test/Microsoft.SqlTools.ServiceLayer.IntegrationTests

**Comment by sawilde** [comment]
Thanks for reporting that - will look into it

**Comment by jtaubensee** [comment]
+1 - We are seeing this on an Appveyor build as well. https://ci.appveyor.com/project/jtaubensee/azure-service-bus-dotnet/build/1.0.288.

Please let me know if you'd like me to provide more details. The stack trace seems to be the same reported by @benrr101

**Comment by sawilde** [comment]
@benrr101 I've pulled your repo but can't get it to build and run tests 100%

> An error occurred when executing task 'TestCore'.
Error: Test Microsoft.SqlTools.ServiceLayer.UnitTests failed for .NET Core.

Is there something missing in my environment?

**Comment by sawilde** [comment]
a fix for this issue can be found here https://ci.appveyor.com/project/sawilde/opencover/build/4.6.684/artifacts

**Comment by benrr101** [comment]
Thanks for the potential fix. I'll pull it down into our repo and run it through appveyor a few times to see if it will work for us. Since it's a race condition issue, it'll be hard to 100% verify that it's working, but if I can complete the coverage build, say, 10 times, I'll say it's good.

Since you've got a fix out, I'm assuming you don't need help getting our build running? If not, I can still help you out with it (I admit, it's kinda wonky sometimes).

**Comment by sawilde** [comment]
> Since you've got a fix out,

Well all I did was review the code and ensure that Dispose could be called multiple times - safely.

**Comment by jtaubensee** [comment]
@sawilde - Thanks for the fix. Since this issue is listed as a part of the `Release (Qn 2017)`, does that mean there won't be a NuGet package for this until June 30th?

**Comment by jtaubensee** [comment]
@sawilde - Actually I'm seeing another error now.

```
At: Program.Main
An System.Threading.SemaphoreFullException occured: Adding the specified count to the semaphore would cause it to exceed its maximum count.
stack:    at System.Threading.Semaphore.Release(Int32 releaseCount)
   at OpenCover.Framework.Manager.MemoryManager.ManagedMemoryBlock.<>c.<Dispose>b__27_0(Semaphore s) in C:\projects\opencover\main\OpenCover.Framework\Manager\MemoryManager.cs:line 163
   at OpenCover.Framework.HelperExtensions.Do[T](T value, Action`1 action) in C:\projects\opencover\main\OpenCover.Framework\HelperExtensions.cs:line 18
   at OpenCover.Framework.Manager.MemoryManager.ManagedMemoryBlock.Dispose(Boolean disposing) in C:\projects\opencover\main\OpenCover.Framework\Manager\MemoryManager.cs:line 160
   at OpenCover.Framework.Manager.MemoryManager.ManagedMemoryBlock.Dispose() in C:\projects\opencover\main\OpenCover.Framework\Manager\MemoryManager.cs:line 151
   at OpenCover.Framework.HelperExtensions.Do[T](T value, Action`1 action) in C:\projects\opencover\main\OpenCover.Framework\HelperExtensions.cs:line 18
   at OpenCover.Framework.Manager.MemoryManager.FetchRemainingBufferData(Action`1 processBuffer) in C:\projects\opencover\main\OpenCover.Framework\Manager\MemoryManager.cs:line 441
   at OpenCover.Framework.Manager.ProfilerManager.ProcessMessages(WaitHandle[] handles) in C:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 237
   at OpenCover.Framework.Manager.ProfilerManager.RunProcess(Action`1 process, String[] servicePrincipal) in C:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 120
   at OpenCover.Console.Program.RunWithContainer(CommandLineParser parser, Bootstrapper container, IPersistance persistance) in C:\projects\opencover\main\OpenCover.Console\Program.cs:line 175
   at OpenCover.Console.Program.Main(String[] args) in C:\projects\opencover\main\OpenCover.Console\Program.cs:line 67
A report has been sent to the OpenCover development team.
If you are unable to resolve the issue please contact the OpenCover development team
see https://www.github.com/opencover/opencover/issues
```

https://ci.appveyor.com/project/jtaubensee/azure-service-bus-dotnet/build/1.0.379#L1836

Can you take a look when you have a chance? Let me know if you need any more information.

**Comment by sawilde** [comment]
@jtaubensee does this happen all the time for you is it intermittent - I don't see these errors myself?

**Comment by sawilde** [comment]
@jtaubensee 
> thanks for the fix. Since this issue is listed as a part of the Release (Qn 2017)
I hope to make a release before then but I am sort of blocked as I want to include .net core support but not be using beta packages from dependant packages

**Comment by jtaubensee** [comment]
@sawilde - I just had a successful run, so it doesn't seem to happen every time.

https://ci.appveyor.com/project/jtaubensee/azure-service-bus-dotnet/build/1.0.381#L1905

**Comment by sawilde** [comment]
@jtaubensee - ah - my favourite kind of defect

**Comment by benrr101** [comment]
Just as a heads up, I've validated the build with my team's project. Everything seems to be working as expected (although since it was likely a race condition, I can never be 100% certain). I haven't seen the semaphore exception @jtaubensee mentioned, tho.

**Comment by sawilde** [comment]
@benrr101 thanks - I have attempted to resolve the semaphore issue (one I've never been able to repeat either)
