### ISSUE TITLE
Opencover + Nunit3 console runner throws NUnitEngineException

### ISSUE THREAD

**Issue by sriv** [OpenCover/opencover#677]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [X] .NET 4.5

### My Environment

- [X] Windows 10

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Opencover + NUnit3.ConsoleRunner + Fake task helper should run nunit tests, and generate coverage report.

Note: this works with NUnit2, but I need to upgrade to NUnit 3.

### Actual Behavior

Running Nunit3 console standalone:

```
Finished Target: RunTests-Lib
Starting Target: RunTests-All (==> CopyBinaries, RunTests-Lib)
C:\Users\steam\projects\gauge\gauge-csharp\packages\test\NUnit.ConsoleRunner\tools\nunit3-console.exe "--noheader" "--timeout=300000" "--result=TestResults.xml" "C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll" "C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\tests\Gauge.CSharp.Runner.UnitTests.dll"
C:\Users\steam\projects\gauge\gauge-csharp\packages\test\NUnit.ConsoleRunner\tools\nunit3-console.exe "--noheader" "--timeout=300000" "--result=TestResults.xml" "C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll" "C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\tests\Gauge.CSharp.Runner.UnitTests.dll"
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10240.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll
    C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\tests\Gauge.CSharp.Runner.UnitTests.dll


Tests Not Run

1) Ignored : Gauge.CSharp.Runner.UnitTests.MethodExecutorTests.ShouldTakeScreenShotOnFailedExecution
Screenshots are not available in CI - to use Gauge_screenshot instead

Run Settings
    DisposeRunners: True
    DefaultTimeout: 300000
    WorkDirectory: C:\Users\steam\projects\gauge\gauge-csharp
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 2

Test Run Summary
  Overall result: Warning
  Test Count: 172, Passed: 171, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 1
    Skipped Tests - Ignored: 1, Explicit: 0, Other: 0
  Start time: 2017-04-13 11:53:33Z
    End time: 2017-04-13 11:54:11Z
    Duration: 37.915 seconds
```

Running Opencover with target=`nunit3-console.exe` yields:

```
OpenCover command
./packages/test/OpenCover/tools/OpenCover.Console.exe -target:"C:\Users\steam\projects\gauge\gauge-csharp\packages\test\NUnit.ConsoleRunner\tools\nunit3-console.exe" -targetargs:"--noheader --shadowcopy=false --timeout=300000 --framework=net-4.5 --result=artifacts/coverage/nunit-results.xml C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\tests\Gauge.CSharp.Runner.UnitTests.dll" -output:"artifacts/coverage/results.xml" -register:user -filter:"+[*]* -[*.*Tests*]* -[*IntegrationTestSample*]*"
./packages/test/OpenCover/tools/OpenCover.Console.exe -target:"C:\Users\steam\projects\gauge\gauge-csharp\packages\test\NUnit.ConsoleRunner\tools\nunit3-console.exe" -targetargs:"--noheader --shadowcopy=false --timeout=300000 --framework=net-4.5 --result=artifacts/coverage/nunit-results.xml C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\tests\Gauge.CSharp.Runner.UnitTests.dll" -output:"artifacts/coverage/results.xml" -register:user -filter:"+[*]* -[*.*Tests*]* -[*IntegrationTestSample*]*"
﻿Executing: C:\Users\steam\projects\gauge\gauge-csharp\packages\test\NUnit.ConsoleRunner\tools\nunit3-console.exe
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10240.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll
    C:\Users\steam\projects\gauge\gauge-csharp\artifacts\gauge-csharp\tests\Gauge.CSharp.Runner.UnitTests.dll

Unhandled Exception: NUnit.Engine.NUnitEngineException: No connection could be made because the target machine actively refused it 127.0.0.1:51037
Failed to stop the remote agent. No connection could be made because the target machine actively refused it 127.0.0.1:51037
   at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.Engine.Runners.TestExecutionTask.Execute()
   at NUnit.Engine.Runners.ParallelTaskWorkerPool.ProcessTasksProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Tests Not Run
```

### Steps to reproduce the problem:

- clone https://github.com/getgauge/gauge-csharp
- Run `.\build.cmd RunTests-All` to see Nunit tests result
- Run `.\build.cmd RunTests-Coverage` to see Opencover in action, and the error.

**Comment by sawilde** [comment]
@sriv currently the build is failing on my machine and I see that your appveyor build is failing for the same reason https://ci.appveyor.com/project/sriv/gauge-csharp

Let me know when it is all good to go again and I'll continue investigating.

**Comment by sriv** [comment]
@sawilde - Sorry about that, the build is fixed now. Please have a look whenever you get a chance. Thanks.

**Comment by sawilde** [comment]
@sriv just to let you know the issue only occurs when it is running the IntegrationTests so if you want to get coverage of your UnitTests you can do that now.

**Comment by sriv** [comment]
@sawilde - thanks for the update and I appreciate you looking into this.

If it helps locate a cause, here is the blob before I updated the NUnit dependency to use NUnit3:

https://github.com/getgauge/gauge-csharp/blob/b9c65660da84d7f1d56395da1871b287c354c4f7

With NUnit2, opencover worked like a charm, even if I included the IntegrationTests in the coverage run.

Please let me know if there is any help I can be of. Happy to contribute in any form.

And I'd like to thank you for all the hard work in Opencover, have been a happy user for years!

**Comment by sawilde** [comment]
@sriv I don't think the issue is with OpenCover

I took your latest source and ran your tests locally with the command you are using (and no OpenCover)

```
O:\issues\nunit_677\gauge-csharp> O:\issues\nunit_677\gauge-csharp\packages\test\NUnit.ConsoleRunner\tools\nunit3-console.exe --noheader --shadowcopy=false --timeout=300000 --framework=net-4.5 --result=nunit-results.xml O:\issues\nunit_677\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll
```

and this was the output

```
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    O:\issues\nunit_677\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll


Errors, Failures and Warnings

1) Error :
An existing connection was forcibly closed by the remote host

Server stack trace:
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-08-19 05:16:15Z
    End time: 2017-08-19 05:16:29Z
    Duration: 14.492 seconds

Results (nunit3) saved as nunit-results.xml

No connection could be made because the target machine actively refused it 127.0.0.1:9635
Failed to stop the remote agent. No connection could be made because the target machine actively refused it 127.0.0.1:9635
```

I then investigated and got the tests running when I removed the `--shadowcopy:false` from the nunit arguments.

I then removed that from the `Build.fsx` and got the coverage running as expected.

```
﻿Executing: O:\issues\nunit_677\gauge-csharp\packages\test\NUnit.ConsoleRunner\tools\nunit3-console.exe
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    O:\issues\nunit_677\gauge-csharp\artifacts\gauge-csharp\itests\Gauge.CSharp.Runner.IntegrationTests.dll


Run Settings
    RuntimeFramework: net-4.5
    DisposeRunners: True
    DefaultTimeout: 300000
    WorkDirectory: O:\issues\nunit_677\gauge-csharp
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 23, Passed: 23, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-08-19 05:45:58Z
    End time: 2017-08-19 05:46:32Z
    Duration: 33.637 seconds

Results (nunit3) saved as artifacts/coverage/nunit-results.xml
Committing...
Visited Classes 33 of 79 (41.77)
Visited Methods 125 of 312 (40.06)
Visited Points 418 of 1043 (40.08)
Visited Branches 169 of 524 (32.25)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 37 of 82 (45.12)
Alternative Visited Methods 166 of 386 (43.01)
Generate OpenCover report
Running packages/test/ReportGenerator/tools/ReportGenerator.exe artifacts/coverage/results.xml artifacts/coverage/html in WD: .
packages/test/ReportGenerator/tools/ReportGenerator.exe artifacts/coverage/results.xml artifacts/coverage/html
Loading report 'O:\issues\nunit_677\gauge-csharp\artifacts\coverage\results.xml'
 Preprocessing report
 Initiating parser for OpenCover
  Current Assembly: Gauge.CSharp.Runner
Initializing report builders for report types: Html
Analyzing 57 classes
 Creating report 1/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.AssemblyLoader)
 Creating report 2/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.AssemblyLocater)
 Creating report 3/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Converters.StringParamConverter)
 Creating report 4/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.ErrorCodeAggregator)
 Creating report 5/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Exceptions.GaugeLibVersionMismatchException)
 Creating report 6/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Exceptions.NotAValidGaugeProjectException)
 Creating report 7/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Extensions.AttributeExtensions)
 Creating report 8/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Extensions.MethodInfoExtensions)
 Creating report 9/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Extensions.StringExtensions)
 Creating report 10/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.GaugeCommandFactory)
 Creating report 11/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.GaugeListener)
 Creating report 12/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.GaugeProjectBuilder)
 Creating report 13/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.LogConfiguration)
 Creating report 14/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.MessageProcessorFactory)
 Creating report 15/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.MethodExecutor)
 Creating report 16/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.MethodScanner)
 Creating report 17/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Models.ExecutionResult)
 Creating report 18/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Models.GaugeMethod)
 Creating report 19/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Models.HookMethod)
 Creating report 20/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Models.HookRegistry)
 Creating report 21/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Models.StepRegistry)
 Creating report 22/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.DataStoreInitProcessor)
 Creating report 23/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.DefaultProcessor)
 Creating report 24/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.ExecuteStepProcessor)
 Creating report 25/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.ExecutionEndingProcessor)
 Creating report 26/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.ExecutionProcessor)
 Creating report 27/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.ExecutionStartingProcessor)
 Creating report 28/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.HookExecutionProcessor)
 Creating report 29/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.KillProcessProcessor)
 Creating report 30/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.RefactorProcessor)
 Creating report 31/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.ScenarioDataStoreInitProcessor)
 Creating report 32/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.ScenarioExecutionEndingProcessor)
 Creating report 33/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.ScenarioExecutionStartingProcessor)
 Creating report 34/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.SpecDataStoreInitProcessor)
 Creating report 35/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.SpecExecutionEndingProcessor)
 Creating report 36/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.SpecExecutionStartingProcessor)
 Creating report 37/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.StepExecutionEndingProcessor)
 Creating report 38/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.StepExecutionStartingProcessor)
 Creating report 39/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.StepNameProcessor)
 Creating report 40/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.StepNamesProcessor)
 Creating report 41/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.StepValidationProcessor)
 Creating report 42/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.SuiteDataStoreInitProcessor)
 Creating report 43/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.TaggedHooksFirstExecutionProcessor)
 Creating report 44/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Processors.UntaggedHooksFirstExecutionProcessor)
 Creating report 45/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Program)
 Creating report 46/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.RefactorHelper)
 Creating report 47/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Sandbox)
 Creating report 48/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.SandboxBuilder)
 Creating report 49/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.SetupCommand)
 Creating report 50/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.StartCommand)
 Creating report 51/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Strategy.HooksStrategy)
 Creating report 52/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Strategy.TaggedHooksFirstStrategy)
 Creating report 53/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Strategy.UntaggedHooksFirstStrategy)
 Creating report 54/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Wrappers.AssemblyWrapper)
 Creating report 55/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Wrappers.DirectoryWrapper)
 Creating report 56/57 (Assembly: Gauge.CSharp.Runner, Class: Gauge.CSharp.Runner.Wrappers.FileWrapper)
 Creating report 57/57 (Assembly: Gauge.CSharp.Runner, Class: System.AssemblyVersionInformation)
 Creating summary
Report generation took 1.1 seconds
Finished Target: RunTests-Coverage

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                Duration
------                --------
AssemblyInfo-Runner   00:00:00.0186954
AssemblyInfo-Core     00:00:00.0051990
AssemblyInfo-Lib      00:00:00.0058721
Build-Lib             00:00:00.8696253
Build-Core            00:00:01.1531760
Build-Runner          00:00:02.2122282
Build                 00:00:00.0002579
Clean                 00:00:00.0698559
CopyBinaries          00:00:08.4047322
RunTests-Coverage     00:00:41.0502048
Total:                00:00:53.9908116
---------------------------------------------------------------------
Status:               Ok
---------------------------------------------------------------------
```

So the solution is:don't use the `--shadowcopy:false` switch

**Comment by sriv** [comment]
Hey @sawilde - thank you very much for following this up. I can confirm that removing `--shadowcopy:false` fixed this.

Wonder why `shadowcopy` would cause this, but I'll pursue that later!

Appreciate all the help. Thanks again for Opencover!

**Comment by sawilde** [comment]
nw - have a good day
