### ISSUE TITLE
Coverage fail because of SerializableException.

### ISSUE THREAD

**Issue by soultingo** [OpenCover/opencover#884]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Steps to reproduce the problem:

Hi, I get this exception when I take coverage code.

```
SerializableException: The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at AxoCover.Models.Testing.Runner.ITestExecutionService.RunTests(TestExecutionTask[] executionTasks, TestExecutionOptions options)
   at AxoCover.Models.Testing.Execution.ExecutionProcess.RunTests(TestExecutionTask[] testExecutionTasks, TestExecutionOptions options)
   at AxoCover.Models.Testing.Execution.TestRunner.RunTests(TestItem testItem, Boolean isCovering, Boolean isDebugging)
   at AxoCover.Models.Testing.Execution.TestRunner.<>c__DisplayClass40_0.<RunTestsAsync>b__0()
```

I open Event Viewer and get that error log:
Source: .Net Runtime
```
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF8BA1B38A0 (00007FF8B9CE0000) with exit code 80131506.
```

My coding environment are:
- Windows 10 Pro
- Visual Studio 2013 Pro
- .Net framework 4.5, platform x64
- NUnit 3.7

**Comment by sawilde** [comment]
Hi @soultingo  

I see you have raised the issue directly with AxoCover

https://github.com/axodox/AxoCover/issues/195

**Comment by soultingo** [comment]
> Hi @soultingo
> 
> I see you have raised the issue directly with AxoCover
> 
> [axodox/AxoCover#195](https://github.com/axodox/AxoCover/issues/195)

Hi @sawilde 
First, I'm so sorry for duplicate issue.
Because, I've searched all issues in AxoCover and I remembered that I've read a similiar issue. (Sorry, I forget the ticket number). They answered the problem indeed OpenCover, so I make a duplicate issue on both side.
Again, I'm sorry about that.

**Comment by sawilde** [comment]
@soultingo if you find it please reference it as I can't think of what it could be.
